### ISSUE TITLE
Missing libraries error on run

### ISSUE THREAD

**Issue by Warniz** [SimRel/Merv1.0#1]
When trying to run the sim in AnyLogic I get an error saying:
`Exception in thread "main" java.lang.ClassNotFoundException: merv_1_0_3.Simulation
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)`

When looking in the problems tab it says:

> Description: Project 'MERV 1_0_BUILD' is missing required library: '/Users/CWT/Downloads/Merv1.0-master 2/bin/gs-algo-1.3.jar'. Location: MERV 1_0 - Model

> Description: Project 'MERV 1_0_BUILD' is missing required library: '/Users/CWT/Downloads/Merv1.0-master 2/bin/gs-core-1.3.jar'. Location: MERV 1_0 - Model

I haven't worked in AnyLogic or java before so any help would be much appreciated.

**Comment by rossgore** [comment]
Hi Each of these graph stream libraries can be found at: http://graphstream-project.org/download/

A thread about adding the libraries into anylogic so the model can execute is here: https://help.anylogic.com/index.jsp?topic=%2Fcom.anylogic.help%2Fhtml%2Flibraries%2FAdding+External+Jar+Files+and+Java+Classes.html
